# Generated by Django 3.2.15 on 2023-03-10 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('account_type', models.CharField(choices=[(1, 'input'), (2, 'output')], max_length=1, verbose_name='account type')),
                ('reminder_type', models.CharField(choices=[(1, 'check'), (2, 'debt')], max_length=1, verbose_name='reminder type')),
                ('time_choice', models.CharField(choices=[(1, 'one day before'), (2, 'two day before'), (3, 'tree day before'), (4, 'week before'), (5, 'month before')], max_length=1, verbose_name='time choice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reminder',
                'verbose_name_plural': 'reminders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('typ', models.CharField(choices=[(1, 'input'), (2, 'output')], max_length=1, verbose_name='type')),
                ('tag', models.CharField(choices=[(1, 'food'), (2, 'dress'), (3, 'bill'), (4, 'rent'), (5, 'leon'), (6, 'salary'), (7, 'cas and accessories'), (8, 'payment to other'), (9, 'service'), (10, 'health'), (11, 'other')], max_length=2, verbose_name='tag')),
                ('is_draft', models.BooleanField(default=False, verbose_name='is draft')),
                ('draft_till', models.DateField(blank=True, null=True, verbose_name='draft till')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ('-created_at',),
            },
        ),
    ]
