# Generated by Django 3.2.15 on 2023-03-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230317_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='draft_till',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='is checked\\\\\\\\'),
        ),
    ]
