# Generated by Django 3.2.15 on 2023-03-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20230319_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='remindermodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
