# Generated by Django 3.2.15 on 2023-03-20 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20230319_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindermodel',
            name='reminding_time',
            field=models.DateField(default=datetime.date(2023, 3, 20), verbose_name='reminding time'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='is checked'),
        ),
    ]
