# Generated by Django 3.2.15 on 2023-03-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230320_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindermodel',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='is visible'),
        ),
    ]
