# Generated by Django 3.2.15 on 2023-03-20 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remindermodel_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermodel',
            name='reminding_time',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 8, 19, 58, 375307, tzinfo=utc), verbose_name='reminding time'),
        ),
    ]
