# Generated by Django 3.2 on 2023-03-21 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20230321_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermodel',
            name='reminding_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='reminding time'),
        ),
    ]
