# Generated by Django 3.2 on 2023-03-21 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_remindermodel_reminding_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermodel',
            name='reminding_time',
            field=models.DateField(default=datetime.date(2023, 3, 21), verbose_name='reminding time'),
        ),
    ]
