MALE = 'Male'
FEMALE = 'Female'
SEX_TYPE_CHOICES = (
    (MALE, 'Male'),
    (FEMALE, 'Female')
)


SATURDAY = 'SATURDAY'
SUNDAY = 'SUNDAY'
MONDAY = 'MONDAY'
TUESDAY = 'TUESDAY'
WEDNESDAY = 'WEDNESDAY'
THURSDAY = 'THURSDAY'
FRIDAY = 'FRIDAY'
CLASS_DATE_CHOICES = (
    (SATURDAY, 'SATURDAY'),
    (SUNDAY, 'SUNDAY'),
    (MONDAY, 'MONDAY'),
    (TUESDAY, 'TUESDAY'),
    (WEDNESDAY, 'WEDNESDAY'),
    (THURSDAY, 'THURSDAY'),
    (FRIDAY, 'FRIDAY'),
)