# Generated by Django 3.2.15 on 2023-03-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermobilemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userphonemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAddressModel',
        ),
        migrations.DeleteModel(
            name='UserEmailModel',
        ),
        migrations.DeleteModel(
            name='UserMobileModel',
        ),
        migrations.DeleteModel(
            name='UserPhoneModel',
        ),
    ]
